---

- name: Get namespace template name from {{ namespace.template_path }}
  set_fact:
    _namespace_template_name: "{{ namespace.template_path.split('/')|last|replace('.yml.j2', '')|replace('.yaml.j2', '') }}"

- name: Generate Envs Namespace dir {{ _namespace_template_name }}
  ansible.builtin.file:
    path: "{{ _current_env_dir }}/Namespaces/{{ _namespace_template_name }}"
    state: directory

- name: Set templates
  set_fact:
    template_override: "{{ namespace.template_override| default('') }}"

- name: Generate Envs Namespace yaml {{ _namespace_template_name }} for {{ namespace.name }}
  ansible.builtin.blockinfile:
    path: "{{ _current_env_dir }}/Namespaces/{{ _namespace_template_name }}/namespace.yml"
    block: "{{ lookup('template', namespace.template_path) }}"
    create: yes

- name: Generate Envs Namespace yaml {{ _namespace_template_name }} for {{ namespace.name }}
  ansible.builtin.blockinfile:
    path: "{{ _current_env_dir }}/Namespaces/{{ _namespace_template_name }}/namespace.yml_override"
    block: "{{ template_override }}"
    create: yes
  when: template_override != ''